baseURL = "https://botfactory.19bit.net"
title = "Bot Factory"
theme = "salinger"

[params]

author = "Erik K Anderson"
#googleAnalytics = ""
twemoji = true
text404 = "Since the page you were looking for seems like doesn't exist, we <strong>strongly</strong> suggest you to better investigate the URL and/or go back to the <a href=\"/\">home</a>."

DateFormat = "Jan 2006"

mainMenuSvg = '''
<svg class="icon w-7 h-7" xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 -960 960 960" width="48"><path d="M110-558q-12.75 0-21.375-8.625T80-588v-10q0-109 105-175.5T480-840q190 0 295 66.5T880-598v10q0 12.75-8.625 21.375T850-558H110Zm32-60h676q-3-69-96.5-115.5T480-780q-148 0-242.5 46.5T142-618ZM80-416q0-8.878 7-17.439T105-447q23-8 45.564-23.5T216-486q54 0 71.5 22t58.5 22q41 0 60.5-22t73.5-22q54 0 73.5 22t60.5 22q41 0 58.5-22t71.5-22q43 0 65.5 15.5T855-447q11.184 5.25 18.092 13.125Q880-426 880-416q0 15.162-10.5 24.081Q859-383 846-386q-32-8-50.5-24t-51.515-16Q703-426 685.5-404T614-382q-54 0-73.5-22T480-426q-41 0-60.5 22T346-382q-54 0-71.5-22t-58.485-22Q183-426 164.5-410T114-386q-13 3-23.5-5.919T80-416Zm60 296q-24 0-42-18t-18-42v-68q0-24.75 17.625-42.375T140-308h680q24.75 0 42.375 17.625T880-248v68q0 24-18 42t-42 18H140Zm0-60h680v-68H140v68Zm2-438h676-676Zm-2 370h680-680Z"/></svg>
'''

# logoSvg = '''
#'''
# logoLabel = "Bot Factory"

mainMenuShowThemes = true
showFooterOnHomepage = true
showHeaderOnHomepage = true
showSocialOnHomepage = true
showOnlyFeaturedPost = true

[params.meta]
title = "Bot Factory"
description = "Bot Factory is a Discord server for learning, building, and growing where everyone contributes"
keywords = ["discord", "server", "bot", "tech", "programming"]

[params.footer]
copy = 'Erik K Anderson'

[[params.social]]
name = "discord"
url = "https://discord.gg/3GbdX6KkQv"
icon = "fa-brands discord"
featured = true # true to be displayed in the home hero.

[Menu]
[[mune.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Join The Discord Server"
url = "https://discord.gg/3GbdX6KkQv"
weight = 2

[taxonomies]
category = "categories"
lang = "langs"
tags = "tags"
tool = "tools"


# the following code is mandatory for the theme to work properly.

[module]
[module.hugoVersion]
extended = false
min = "0.112.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "styles\\.css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'base16-snazzy'
